apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
  
replicas:
  - name: vote
    count: 8

images:
  - name: schoolofdevops/vote
    newTag: v8 # {"$imagepolicy": "flux-system:vote:tag"}
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@example.com"

configMapGenerator:
  - name: vote
    literals:
      - OPTION_A=STAGING
      - OPTION_B=DEV

