apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-1
  creationTimestamp: null
  labels:
    app: vote
    name: vote-1
spec:
  minReadySeconds: 20
  replicas: 3
  selector:
    matchLabels:
      app: vote
      name: vote-1
  template:
    metadata:
      labels:
        app: vote
        name: vote-1
    spec:
      containers:
      - image: schoolofdevops/vote:v4
        name: vote
